### ISSUE TITLE
Workshops filter by curriculum 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#109]
In the workshops filter page ([preview](https://tnd-carpentries-website.netlify.app/workshops/upcoming-workshops/)), the list of curricula is not building properly.  It begins with `and/or OpenRefine` when pulling curricula from our [curriculum feed](https://feeds.carpentries.org/amy_curricula.json) and then includes a broken list of options.  Each item's `name` value should be an item in the curriculum filter list.  Maybe commas are not being properly escaped?

**Comment by AdamChlan** [comment]
@maneesha we are using this feed https://feeds.carpentries.org/amy_curricula.json to map the ID of the curriculum referenced in the worskhop [feed](https://feeds.carpentries.org/all_upcoming_workshops.json) with the object in the curricula feed and get its proper name. Problem is this feed does not have clean names. Ex: Data Carpentry (Geospatial) *Note: Available for Self-Organised workshops only

We think it would be best for you to either clean up the names in the curricula feed or give us the full names of the curriculum in the workshop feed.

You can preview this here: https://deploy-preview-115--tnd-carpentries-website.netlify.app/workshops/upcoming-workshops/

**Comment by maneesha** [comment]
The list of curricula does not change often, so in that case I think data that is maintained internal to the website would actually make more sense.  What format should this data set take?  I can put that together.

**Comment by AdamChlan** [comment]
YAML would be good. we currently use an id, name, description from the feed

**Comment by maneesha** [comment]
I see you use the name & id. Where do you use the description?

**Comment by AdamChlan** [comment]
Right, we were just discussing that internally. We think you can leave out description

**Comment by AdamChlan** [comment]
yes, in the /data folder

**Comment by AdamChlan** [comment]
@maneesha we going to need to confer with Regis on this. he is currently on vacation and will return on Monday June 24. We will prioritize having him wrap this task up then. And then we can plan on having him complete the packaging of the theme.

**Comment by AdamChlan** [comment]
@maneesha We have this resolved in the main branch. Please have a look, and confirm things look good on your end.

Also, we are ready to package up the theme, if you are ready.

**Comment by maneesha** [comment]
Re-closing as this looks good!
