### ISSUE TITLE
Current tab should be styled in tabbed navigation

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#25]
Current tab should be styled in tabbed navigation like on the [About page (preview)](https://deploy-preview-24--tnd-carpentries-website.netlify.app/about-us/).

**Comment by AdamChlan** [comment]
we will add an underline as an active state, unless you have another preference.

**Comment by maneesha** [comment]
Underline is fine.  It looks like it is not working in the  [About](https://tnd-carpentries-website.netlify.app/about-us/) section but is working in the [Workshops](https://tnd-carpentries-website.netlify.app/workshops/) section.  I'm not sure what the difference is between them.
