### ISSUE TITLE
Filtering options on pages with lists of workshop

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#29]
On the sidebar, the "search" feature should perform a full text search of workshop data.  
We do not want to see another "filter" menu button as currently exists on some of our prototypes. 
The sidebar should allow filtering by the following three categories (using **_and_** (not **_or_**) logic when used in combination): 

* **Country**: Options should be dynamically generated from all distinct countries in [this feed](https://feeds.carpentries.org/all_workshops.json) 
* **Workshop delivery**: two options - Online or In-person
* **Curriculum**: Options should be:
  - Data Carpentry: Astronomy
  - Data Carpentry: Ecology
  - Data Carpentry: Genomics
  - Data Carpentry: Geospatial
  - Data Carpentry: Image Processing
  - Data Carpentry: Social Sciences
  - Library Carpentry
  - Software Carpentry (Plotting and Programming in Python)
  - Software Carpentry (Programming with Python)
  - Software Carpentry (Programming with R)
  - Software Carpentry (R for Reproducible Scientific Analysis)

In terms of design, these can take the form of simple `<select>` elements in the sidebar instead of the card/button display we currently see.

**Comment by AdamChlan** [comment]
@maneesha We noticed that the prototype does not have pagination on the future or past event pages. If we can build this without pagination, we have a straightforward plan for implementation. But please let us know if pagination is required, and we will need to find another way.

**Comment by maneesha** [comment]
How will this affect load time? Right now [the list is not paginated](https://carpentries.org/past_workshops/).  Given we have close to 4000 workshops listed, and this list will only continue to grow, as long as it doesn't slow down load time, we don't need pagination.

**Comment by regisphilibert** [comment]
@AdamChlan I pushed the [branch](https://github.com/carpentries/tnd-carpentries-working/tree/regisphilibert/issue29) and created a PR if you want to improve styling and mobile.

**Comment by AdamChlan** [comment]
@regisphilibert I pushed up some cleanup. I moved the filters to the top on mobile. we can see what is preferred on that one.
