### ISSUE TITLE
Option to dynamically generate statistics 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#30]
When we use these bubbles with stats in them, we want to be able to dynamically generate these numbers.  For example, the number of countries may be the number of unique countries in [this feed](https://feeds.carpentries.org/all_workshops.json).  The number of workshops may be the length of the same feed.  The number of members may be the length of [this feed](https://feeds.carpentries.org/all_public_memberships.json).

![image](https://github.com/carpentries/tnd-carpentries-working/assets/829690/9333586e-49b3-400f-95b4-c37fc0879f24)

From what I can tell, this can be done in shortcodes which are then used in content pages, but not directly in content pages.  Is this correct?

**Comment by AdamChlan** [comment]
@maneesha We did some testing on our end and the following code will allow you to set a site parameter, and output it: 

`{{< param "param_handle_here" >}}`

This would be our recommended path for setting those number, rather than counting from the feed.

**Comment by maneesha** [comment]
Thanks. Is there a way we can have live/dynamic stats?  These numbers will change regularly.

**Comment by regisphilibert** [comment]
Can you detail where the numbers would come from for each stat?

**Comment by regisphilibert** [comment]
I added the label Needs Client Feedback as this will become actionable once the new feed is created.

**Comment by maneesha** [comment]
As a prototype, can we use the `n_trainers` and `n_instructors` values from [this feed](https://feeds.carpentries.org/badges_stats.json)?

**Comment by maneesha** [comment]
This all looks good.
