### ISSUE TITLE
Additional person profile layouts for Core Team & Governance

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#37]
In addition to the person profile layout created that are used in pages like Trainer, Instructor, etc. we also should have layouts to use for our Governance and Core Team pages.

Governance page

* [Governance page (rendered)](https://carpentries.org/governance/)
* [Governance page (source code)](https://github.com/carpentries/carpentries.org/edit/main/pages/governance.html)
* [Governance profile data source](https://github.com/carpentries/carpentries.org/blob/main/_data/governance.yml)
* [Governance profile layout](https://github.com/carpentries/carpentries.org/blob/main/_includes/governance_profiles.md)
  
Core Team page

* [Core Team page (rendered)](https://carpentries.org/team/)
* [Core Team page (source code)](https://github.com/carpentries/carpentries.org/edit/main/pages/team.html)
* [Core Team data source](https://github.com/carpentries/carpentries.org/blob/main/_data/team.yml)
* [Core Team profile layout](https://github.com/carpentries/carpentries.org/blob/main/_includes/team.html)

**Comment by regisphilibert** [comment]
@AdamChlan I've pushed on main the logic for using the same shortcode and persons template for those. So you can branch out from main for the following: 
You can check the `team.md` page.

- [ ] Update the icons (missing just have default link icon) with the proper ones for those services. We'll try and match the current site with fontawesome availasble icon's svgs.
- [ ] The team page uses two shortcodes, one for the `et` and one for the rest of the staff. Currently those rows are centered. (only time it happens) I'm not sure how to reproduce this while maintaining consistency across the site with the solution built. But we can discuss
