### ISSUE TITLE
Handling redirects in Hugo

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#45]
As we reorganize the website and move from Jekyll to Hugo, there will likely be many pages we need to redirect.  In Jekyll, we are currently using the [redirect-to plugin](https://github.com/jekyll/jekyll-redirect-from).  This works but requires the source file for each page to exist so it isn't ideal, as old files still clutter the project. 

What options are there for Hugo to manage redirects? (Or is this better to do server-side, for example with `.htaccess` file?)

**Comment by AdamChlan** [comment]
@maneesha I Hugo you can use aliases - https://gohugo.io/methods/page/aliases/

You would have your new file, and you could add front matter info for any old URL you need to redirect to this new page.

**Comment by regisphilibert** [comment]
Yes Hugo also can get the date from the filename using the site config:
```
frontmatter:
  date:
  - :filename
  - :default
```

**Comment by maneesha** [comment]
Thanks @AdamChlan. I think this will work to redirect **from** pages within the current site but there will also be instances where we may want to redirect **to** an external site.  Does Hugo have a way to handle this?

**Comment by regisphilibert** [comment]
No it won't work for redirects, we'll have to produce our own  `_redirects` file for netlify to process using custom output formats.

I think we'll give you a data file to add the desired redirects (from and to) plus code etc... But we'll also use the `aliases` set in frontmatter to add the simple redirects as well.

**Comment by maneesha** [comment]
Thanks.  Note we use Netlify as a way to have easy previews of sites but this website will actually be hosted on AWS.

**Comment by regisphilibert** [comment]
@maneesha I've added an example on https://github.com/carpentries/tnd-carpentries-working/blob/main/content/about-us/newsletter.md as the current uses `/newsletter` and this one `/about-us/newsletter` it stood a good practical example.

It works as expected

**Comment by AdamChlan** [comment]
@maneesha We are going to close this out, but let us know if you have any further questions.
