### ISSUE TITLE
Overriding styles 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#46]
What options are there for overriding styles?
For example, the [table style](https://github.com/carpentries/tnd-carpentries-working/blob/main/themes/carpentries/assets/css/styles.css#L69) is set to alternate colors using  `#f2f2f2`.  Can we override this color on specific tables? 

(Note the table styling is just an example; I am interested in options for overriding other styles as well.)

**Comment by maneesha** [comment]
With our current Jekyll site, I'm able to add inline css to override global css settings. That does not seem to work here.

**Comment by AdamChlan** [comment]
@maneesha Do you have a few color you are looking to support, or are you looking for the full gamut of colors?

**Comment by maneesha** [comment]
We don't have specifics now.  This was more a general question about how we may be able to override styles.

**Comment by AdamChlan** [comment]
@maneesha can you share an example this being done on the Jekyll site?

**Comment by maneesha** [comment]
Closing this as it looks like when we've done it before we have re-written inline css entirely.
