### ISSUE TITLE
Create newsletter page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#49]
A [placeholder newsletter page is here](https://tnd-carpentries-website.netlify.app/about-us/newsletter/).

- [x] #58
- [x] #59

**Comment by regisphilibert** [comment]
@maneesha I created two shortcodes and added them to the placeholder page here: https://carpentries.netlify.app/about-us/newsletter/

**Comment by maneesha** [comment]
Thanks @regisphilibert 
Can this be styled to be side by side as they are on our current page?

**Comment by regisphilibert** [comment]
Can you take another look @maneesha. Nothing crazy, just utilizing a grid shortcode and removing the sidebar.

**Comment by maneesha** [comment]
This looks good.
