### ISSUE TITLE
Display chosen filters when filtering workshops 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#53]
On our list of past and upcoming workshops, when the user selects filters, can the filtered options be displayed so the user knows what filters are active?

**Comment by AdamChlan** [comment]
@maneesha the dropdown filter will show the active category once it's selected. Once we fix the bug where multiple countries are allowed, this should fix the situation.

**Comment by AdamChlan** [comment]
Noting that this issue has been resolved. Closing out.
