### ISSUE TITLE
Workshop filters should use OR logic within categories; AND logic  across categories 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#54]
This seems to work right now within categories but not across categories.

For example, in "country" if I choose "Canada" and "Ethiopia" I get workshops that are in either Canada OR Ethiopia.
If I then choose "Data Carpentry (Genomics)" without clearing the filter, I now see Data Carpentry (Genomics) workshops in all countries, and the last country I chose remains active in the country selector.  What I would expect is to see all Genomics workshops in the selected countries.

The order in which selections are made seems to impact this. For example, if I choose two curricula first, I see workshops with those two curricula. If I then choose a country, the curriculum stays visible in the selector but I see all workshops in that country.

**Comment by AdamChlan** [comment]
@maneesha we noticed that there is a bug on the existing implementation — when you select one country and then another, the first country remains in the results. We are going to fix this, and then we will plan on keeping this filtering system on the simpler side. Only 1 factor per dropdown will be available.

**Comment by regisphilibert** [comment]
Just pushed the fix discussed above @maneesha

**Comment by maneesha** [comment]
The workshops page looks good to me - I think this issue can be closed.
