### ISSUE TITLE
Viewing blog posts by tags & authors

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#55]
We have talked about this already so it may be something you all are already working on.  Opening an issue just so we don't lose track of this.  

**For tags:**
Right now I can click on a tag to view blog posts with that tag, but we should also have a page that lets users browse all tags, similar to [this current page](https://carpentries.org/blog/posts-by-tags/). 
The url for a tag currently is, for example: `<base-url>/tags/community/`
In order to keep links working from our current site the url should be `<base-url>/blog/posts-by-tags/#blog-tag-community`

**For authors:**
Clicking on an author's name should take you to a view of all posts by that author.  Additionally, as for tags, we should have a page that lets users browse all authors, similar to [this current page](https://carpentries.org/blog/posts-by-authors/). 
 I don't think this should be dependent on the new authoring system we are trying, but please let me know if it would be.
As for tags, we should follow the same url pattern for posts by author:  `<base-url>/blog/posts-by-authors/#blog-author-kari-l.-jordan`

**Comment by AdamChlan** [comment]
@maneesha we see that you have a PR open to get the old blog posts into the site. are you ready to merge that in? We need that content to move forward on this.

**Comment by regisphilibert** [comment]
Yes Hugo also can get the date from the filename using the site config:
```
frontmatter:
  date:
  - :filename
  - :default
```

**Comment by regisphilibert** [comment]
Yes @maneesha  Hugo also can get the date from the filename using the site config:
```
frontmatter:
  date:
  - :filename
  - :default
```

**Comment by AdamChlan** [comment]
@maneesha once you merge in, we can confirm that all is good with the date.

**Comment by regisphilibert** [comment]
I've got this setup. We're going to drop the system I advised you to pick in favor of taxonomies, as authors are now a very simple taxonomy. 

This means as have it now in your markdown file, authors are added using their full name:
```
authors: 
- John Doe
- Jane Smith
```

You can still add front-matter info to some if needed using the following file stucture:
```

- `/content/authors/john-doe/_index.md`
- `/content/authors/jane-smith/_index.md`

Note the `_` in `_index.md` is critical.

**Comment by regisphilibert** [comment]
@maneesha I updated the URLs above following https://github.com/carpentries/tnd-carpentries-working/commit/b61f57651ebe8ab2e5ad20eacf0a02857bc376c9

I don't you you had pages for a single term before `/blog/tag/accessibility`?

**Comment by maneesha** [comment]
@AdamChlan Is this what you are asking about? 
Example page by blog tag - https://carpentries.org/blog/posts-by-tags/#blog-tag-accessibility

**Comment by AdamChlan** [comment]
@maneesha I merged this in. We now have the URL structure set up so it matches what you currently have. Here are a couple examples:

https://deploy-preview-91--tnd-carpentries-website.netlify.app/blog/posts-by-tags/#blog-tag-accessibility
https://deploy-preview-91--tnd-carpentries-website.netlify.app/blog/posts-by-authors/#blog-author-adina-howe

You will also notice that we have individual pages for the tags, which link off of the tag heading on the links above. Do you want to maintain those?

https://deploy-preview-91--tnd-carpentries-website.netlify.app/blog/author/adina-howe/
