### ISSUE TITLE
Testimonial carousel not working properly

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#65]
When I build the site locally, here is what I see:
[screencast of testimonial carousel](https://github.com/carpentries/tnd-carpentries-working/assets/829690/2a478785-1968-40d6-ad9c-7705d4524708)

In the netlify preview of PR #63, only three of the four testimonials display, and the arrow navigation on the sides and the dots underneath do not do anything.

**Comment by AdamChlan** [comment]
@maneesha Yes, we have this on our list of things to address.

**Comment by AdamChlan** [comment]
@maneesha I merged a fix for this into the main branch
