### ISSUE TITLE
Set up lessons page with filtering/searching 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#68]
See PR #67 that creates the [lessons page](https://tnd-carpentries-website.netlify.app/lessons/). This page should be similar to the [workshops page](https://tnd-carpentries-website.netlify.app/workshops/upcoming-workshops/) in how it sets up cards and allows searching and filtering.

**Comment by regisphilibert** [comment]
Yes CSV is tricky in Hugo and I would recommend switching to a more human readable format. Blue sky wish it would come form yet another feed to bring more consistency to the code, but a data file is fine.

In any case do you think it would be ok to rename the keys used in this file, as they are not very programming friendly at the moment:

maybe from 
```
Lesson Program: SWC
Name: Version Control with Git
Description: An introduction to working with Git and GitHub, for researchers and others who want to learn how to track versions of their files and collaborate more easily on projects.
By-Tool: Git
By-Skill: Collaborating
Language: English
Domain: General
Link-Url: http://swcarpentry.github.io/git-novice
```
To 

```
program: SWC
name: Version Control with Git
description: An introduction to working with Git and GitHub, for researchers and others who want to learn how to track versions of their files and collaborate more easily on projects.
tool: Git
skill: Collaborating
language: English
domain: General
url: http://swcarpentry.github.io/git-novice
```

If ok I would perform the transformation myself on my branch.

**Comment by maneesha** [comment]
Yes, this sounds great.  Also if we can implement the suggestion in #73 it would help us if we wanted to implement other pages that were "catalogs" of things to be searched/filtered.

**Comment by regisphilibert** [comment]
@maneesha we have a working page now on https://carpentries.netlify.app/lessons/. 

Flags: We do not have images whose filename matches languages, only countries, so I'm not sure how we can handle this as is. But I would advise against using flags for languages, as most languages belong to many countries and limiting them to a single flag can be restrictive.

For the program we do have some logos in the production repo but they don't use the same colors as on your image.

**Comment by maneesha** [comment]
This looks great!! 
I completely agree with you about the flags, so for language I there should not be a corresponding image.
We're in the process of cleaning up some logos so I will share that with you next week.

**Comment by maneesha** [comment]
For logos, you can use the logos found here for now: https://docs.carpentries.org/topic_folders/communications/resources/logos.html#links-to-logo-files

**Comment by maneesha** [comment]
This all looks good!
