### ISSUE TITLE
Create a more generic list/filtering page

### ISSUE THREAD

**Issue by regisphilibert** [carpentries/tnd-carpentries-working#73]
See in #68  and later the blog

Currently the filters really revolves around workshops, we should make this layout agnostic. It should take a feed parameter and maybe a list of filters. not sure.

**Comment by maneesha** [comment]
I like this idea a lot and I think this is what I was originally hoping for.  So the layout would take some data feed (in yaml format if need be, otherwise maybe json or csv).  Each card layout would take parameters from the data feed.  Then we could filter by specified fields in the data feed.

**Comment by regisphilibert** [comment]
Well currently the data structure is very different from one source to the next... So we have to know what keys goes where etc... which makes each feed to filter solution not quiet reusable among different content types.

If the sources (data or feed) were consistently structured expecting a `title` (currently the Workshop title is their location), `subtitle`, `metas` (for tags with icon and filters) etc... We could build something reusable.

**Comment by maneesha** [comment]
We could have data match a standardized format.  We'd ensure that any transformations needed happened outside of the website build (in the process of building our own data feeds).
