### ISSUE TITLE
Side bar for blog list page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#80]
The blog landing page ([example](https://tnd-carpentries-website.netlify.app/blog/)) should have a sidebar to link to blog posts by tag and author, as well as blog archive similar to our [current site](https://carpentries.org/blog/).

Currently the blog lists all posts on one page.  Consider listing only XX pages on the landing page and then paginate through the archive by XX pages, where XX is a number we can modify.

**Comment by AdamChlan** [comment]
@maneesha is the only difference between the main blog page, and the blog archive page, is that one is paginated and one is not?

**Comment by maneesha** [comment]
On our current site, the [main blog page](https://carpentries.org/blog/) lists the 15 most recent entries, while the [blog archive page](https://carpentries.org/blog/archive/) lists **all** blog posts in one page.  IIRC, this was because the jekyll template was doing some annoying thing when it came to pagination for the archives so we just left it all on one page.  

We could have this set up where everything is just paginated, so the main blog page is essentially page 1 of the paginated archives.

**Comment by AdamChlan** [comment]
@maneesha I updated the blog landing page to have the sidebar links, and it is now paginated:

https://tnd-carpentries-website.netlify.app/blog/

**Comment by maneesha** [comment]
Looks good to me!
