### ISSUE TITLE
Move hardcoded content in footer out of layout

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#83]
The [footer layout](https://github.com/carpentries/tnd-carpentries-working/blob/main/themes/carpentries/layouts/partials/footer.html) has a lot of hardcoded content.  

This should be moved out of the footer layout so it can be modified for each site that uses this theme.

**Comment by maneesha** [comment]
Remove from footer in the layout and have each site code in that content.

**Comment by AdamChlan** [comment]
@maneesha I have moved the hard coded content out of the layout, and included them as partials. They can be updated as needed on a site by site basis. Let me know if you need anything else here.

**Comment by maneesha** [comment]
@AdamChlan It looks like the content is still in the theme though.  We'd want that moved to the site content so each site that uses this theme can customize the footer content.

**Comment by AdamChlan** [comment]
@maneesha We have a few options here for controlling this content. Please let me know if you have a preference or any questions.

1. You can build the footer menus through the site config file. This is how the main navigation is being constructed.
2. You can have a custom HTML file that will override the theme's footer partial
3. Or we can allow for front matter flags to construct these footer menus. This in our opinion would be hardest to manage.

**Comment by maneesha** [comment]
By option 1 above, do you mean something like the [menus.yaml](https://github.com/carpentries/tnd-carpentries-working/blob/main/config/_default/menus.yaml) file?

If so, I think that is what we would prefer to keep things consistent.

**Comment by AdamChlan** [comment]
@maneesha Yes, like the menus.yaml file. We can get that in place

**Comment by maneesha** [comment]
Following up on this, the links to the socials (Facebook, Twitter, etc.) should also be moved out of the theme and into the site content.  

Icons should also only display if a link is provided in the site content.

**Comment by AdamChlan** [comment]
@maneesha I have the socials moved out to the menu file as well now
