### ISSUE TITLE
Supporters logo grid should adapt to number of items

### ISSUE THREAD

**Issue by maneesha** [carpentries/tnd-carpentries-working#85]
The [supporters logo grid](https://github.com/carpentries/tnd-carpentries-working/blob/main/themes/carpentries/layouts/partials/blocks/templates/logo-grid.html) should adapt to the number of items in the list. 

Currently it seems set to 4 items but want to be able to display fewer or more. I know this may be tricky when the number of items does not fit the grid size so I am open to ideas on how to make this work.

**Comment by AdamChlan** [comment]
@maneesha I converted this to flexbox so it will layout better. Let me know if you need anything else here.
