### ISSUE TITLE
Investigate blog post permalinks

### ISSUE THREAD

**Issue by regisphilibert** [carpentries/tnd-carpentries-working#89]
It seems we need to isolate the slug from the date in the filename 

`/content/posts/2022/11/2022-11-02-dovetail-010.md` must live at `/blog/2022/11/dovetail-10`.

Not sure how to achieve this considering there is not slug set.

**Comment by regisphilibert** [comment]
We don't really have a solution for this. We can ask Hugo to determine the date of a blog post from its filename if no date is found. This works well in conjuncture of the permalink being generated from the date.

The problem is that the permalink behaviour will depend on the file having a date set through front matter or not because of Hugo peculiarity.

If a date is found, the slug will be left intact, so our example above will live at `/blog/2022/11/2022-11-02-dovetail-010`, if a date is not found and Hugo needs to infer it from the filename, it will be smart enough to remove its "date portion" from the said filename when printing the URL and the file will live at `/blog/2022/11/dovetail-010`.

But now we end up with a different URL structure depending on a date being set in front matter or not...

There two options:
1. Have all posts rely on their filename to build the date, but this will mean updating the date through front-matter is now impossible, and editors will have to change the filename to update the date.
2. Remove the date from the filename on all posts and rely on the front-matter to infer the date.

**Comment by maneesha** [comment]
Can we do a variation of option 2 - where we keep the date in the filename, and then rely on the date explicitly identified in the  frontmatter?  (Which may just mean we don't do anything) 

I have written scripts to update frontmatter before, so I could do that on our blog archives before the site goes live.

**Comment by regisphilibert** [comment]
Unfortunately I did not find a way to do that. This is how Hugo allows you to determine what to use in order to infer the date of a given entry.
```
frontmatter:
  date:
  - :default
  - :filename
```

With the above, it will use the default date inferring logic (frontmatter) and if it does not find a date with it, will look at the filename.

The problem is that it correctly ignores the date part of the filename when generating the URL **only** when using the `:filename` logic. So if it finds the date in the front matter (using the `:default` logic), it will keep it in the url producing `/blog/2024-02-02-my-title` instead of `/blog/my-title`.

That's why our only option without renaming the files is to use `:filename` on all files and ignore the front-matter... Not an ideal solution I must admit but I have yet to find a better one...

**Comment by maneesha** [comment]
That's why I was thinking we'll just stick with the dates in the frontmatter.  We have historic blog posts that are missing dates in the frontmatter (dates are only in the filename), and these will produce errors.  We'll take care of cleaning that up ourselves.

**Comment by regisphilibert** [comment]
Sounds good, but without renaming the file, the url for the post will be `/blog/2022-01-02-my-title` do you confirm?

**Comment by maneesha** [comment]
Yes, and we will clean up blog post filenames and frontmatter on our end. This does not need to be incorporated into the Hugo theme.
